### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by thesimpledata** [IBM/instana-openshift#4]
I am getting this error. Any help would be appreciated

 YN0002: │ ui-frontend@workspace:services/ui/frontend doesn't provide keycharm@^0.2.0 || ^0.3.0 requested by vis-network@npm:7.9.0
➤ YN0002: │ ui-frontend@workspace:services/ui/frontend doesn't provide moment@^2.24.0 requested by vis-network@npm:7.9.0
➤ YN0002: │ ui-frontend@workspace:services/ui/frontend doesn't provide timsort@^0.3.0 requested by vis-network@npm:7.9.0
➤ YN0002: │ ui-frontend@workspace:services/ui/frontend doesn't provide uuid@^3.4.0 || ^7.0.0 || ^8.0.0 requested by vis-network@npm:7.9.0
➤ YN0002: │ ui-frontend@workspace:services/ui/frontend doesn't provide vis-data@^6.2.1 requested by vis-network@npm:7.9.0
➤ YN0002: │ ui-frontend@workspace:services/ui/frontend doesn't provide vis-util@^3.0.0 || ^4.0.0 requested by vis-network@npm:7.9.0
➤ YN0002: │ vis-network@npm:5.4.1 doesn't provide uuid@^7.0.0 || ^8.0.0 requested by vis-data@npm:6.6.1
➤ YN0060: │ vis-network@npm:5.4.1 provides vis-util@npm:1.1.10 with version 1.1.10 which doesn't satisfy ^4.0.0 requested by vis-data@npm:6.6.1
➤ YN0000: └ Completed in 0.25s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.79s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 5.47s
➤ YN0000: Done with warnings in 6.7s
[+] Building 2.5s (9/11)                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                0.0s
 => => transferring dockerfile: 450B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                   0.0s
 => => transferring context: 34B                                                                                                    0.0s
 => [internal] load metadata for docker.io/thesimpledata/node-base:v1                                                               0.0s
 => [internal] load build context                                                                                                   0.0s
 => => transferring context: 5.82kB                                                                                                 0.0s
 => [ui 1/4] FROM docker.io/thesimpledata/node-base:v1                                                                              0.0s
 => CACHED [release 2/4] WORKDIR /services/ui/backend                                                                               0.0s
 => CACHED [ui 2/4] WORKDIR /services/ui/frontend                                                                                   0.0s
 => CACHED [ui 3/4] COPY frontend .                                                                                                 0.0s
 => ERROR [ui 4/4] RUN yarn build                                                                                                   2.2s
------
 > [ui 4/4] RUN yarn build:
#9 2.172 Internal Error: Unable to deserialize cloned data due to invalid or unsupported version.
#9 2.172     at Object.deserialize (v8.js:289:7)
#9 2.172     at T.restoreInstallState (/.yarn/releases/yarn-berry.js:42:125998)
#9 2.172     at processTicksAndRejections (internal/process/task_queues.js:93:5)
#9 2.172     at async c.execute (/.yarn/releases/yarn-berry.js:50:49242)
#9 2.172     at async c.validateAndExecute (/.yarn/releases/yarn-berry.js:16:48146)
#9 2.172     at async c.run (/.yarn/releases/yarn-berry.js:42:55077)
#9 2.172     at async s.execute (/.yarn/releases/yarn-berry.js:50:22957)
#9 2.172     at async s.validateAndExecute (/.yarn/releases/yarn-berry.js:16:48146)
#9 2.172     at async c.run (/.yarn/releases/yarn-berry.js:42:55077)
#9 2.172     at async c.runExit (/.yarn/releases/yarn-berry.js:42:55211)
------
executor failed running [/bin/sh -c yarn build]: exit code: 1
shakilkhan@Shakils-MacBook-Pro instana-openshift %

**Comment by maheshwarishikha** [comment]
@thesimpledata which step did you face this error?

If it is during execution of `build-and-deploy.sh` then seems to be some version mismatching. It seems to be working fine for me with the following versions:
```
% yarn -v
2.0.0-rc.32
% node -v
v16.8.0
% npm -v
7.21.0
```
